class Sequential(Module):
  __parameters__ = []
  __buffers__ = []
  training : bool
  _is_full_backward_hook : Optional[bool]
  __annotations__["0"] = __torch__.ultralytics.nn.modules.conv.Conv
  __annotations__["1"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_2.Conv
  __annotations__["2"] = __torch__.ultralytics.nn.modules.block.C2f
  __annotations__["3"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_24.Conv
  __annotations__["4"] = __torch__.ultralytics.nn.modules.block.___torch_mangle_60.C2f
  __annotations__["5"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_63.Conv
  __annotations__["6"] = __torch__.ultralytics.nn.modules.block.___torch_mangle_99.C2f
  __annotations__["7"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_102.Conv
  __annotations__["8"] = __torch__.ultralytics.nn.modules.block.___torch_mangle_124.C2f
  __annotations__["9"] = __torch__.ultralytics.nn.modules.block.SPPF
  __annotations__["10"] = __torch__.torch.nn.modules.upsampling.Upsample
  __annotations__["11"] = __torch__.ultralytics.nn.modules.conv.Concat
  __annotations__["12"] = __torch__.ultralytics.nn.modules.block.___torch_mangle_152.C2f
  __annotations__["13"] = __torch__.torch.nn.modules.upsampling.___torch_mangle_153.Upsample
  __annotations__["14"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_154.Concat
  __annotations__["15"] = __torch__.ultralytics.nn.modules.block.___torch_mangle_176.C2f
  __annotations__["16"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_179.Conv
  __annotations__["17"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_180.Concat
  __annotations__["18"] = __torch__.ultralytics.nn.modules.block.___torch_mangle_202.C2f
  __annotations__["19"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_205.Conv
  __annotations__["20"] = __torch__.ultralytics.nn.modules.conv.___torch_mangle_206.Concat
  __annotations__["21"] = __torch__.ultralytics.nn.modules.block.___torch_mangle_228.C2f
  __annotations__["22"] = __torch__.ultralytics.nn.modules.head.Detect
