name: "vae"
platform: "onnxruntime_onnx"
max_batch_size: 8
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 512, 512 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 3, 512, 512 ]
  }
]
instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
model_warmup {
  batch_size: 8
}
